import BackButton from "@/components/BackButton";

export default function TermsOfServicePage() {
  const updated = new Date().toLocaleDateString();

  return (
    <main className="bg-(--background) min-h-dvh">
      <header className="p-4 mb-2 shadow-sm w-full">
        <div className="flex items-center justify-between">
          <BackButton />
          <h1 className="text-[22px] font-semibold tracking-tight text-black/90">
            Terms of Service
          </h1>
          <div className="w-12" aria-hidden="true" />
        </div>
      </header>

      <section className="w-11/12 mx-auto max-w-3xl pb-16">
        <div className="rounded-sm border border-black/10 bg-white p-6 sm:p-8">
          <p className="text-sm text-black/55">Last updated: {updated}</p>

          <h2 className="mt-6 text-lg font-semibold text-black/90">
            1. Agreement to Terms
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-black/70">
            By accessing or using Nuance Translate (“Service”), you agree to be
            bound by these Terms of Service (“Terms”). If you do not agree, do
            not use the Service.
          </p>

          <h2 className="mt-6 text-lg font-semibold text-black/90">
            2. The Service
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-black/70">
            Nuance Translate provides AI-powered translation features, including
            optional settings such as dialect, tone, plurality, and gender. You
            are responsible for how you use outputs from the Service.
          </p>

          <h2 className="mt-6 text-lg font-semibold text-black/90">
            3. OpenAI Processing Notice
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-black/70">
            When you submit text for translation, that text (and related request
            settings) is transmitted to and processed by OpenAI to generate the
            translation. Do not submit sensitive, confidential, or personal
            information you do not have the right to share.
          </p>

          <h2 className="mt-6 text-lg font-semibold text-black/90">
            4. Acceptable Use
          </h2>
          <ul className="mt-2 list-disc pl-5 text-sm leading-relaxed text-black/70 space-y-2">
            <li>Do not use the Service for unlawful purposes.</li>
            <li>
              Do not attempt to disrupt, reverse engineer, or abuse the Service.
            </li>
            <li>
              Do not submit content you do not own or have permission to use.
            </li>
          </ul>

          <h2 className="mt-6 text-lg font-semibold text-black/90">
            5. Content and Outputs
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-black/70">
            You retain any rights you have in text you submit. Translations are
            generated by an AI model and may be inaccurate or inappropriate.
            You are responsible for reviewing outputs before relying on them.
          </p>

          <h2 className="mt-6 text-lg font-semibold text-black/90">
            6. Privacy
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-black/70">
            Your use of the Service is also governed by our Privacy Policy and
            Cookie Policy.
          </p>

          <h2 className="mt-6 text-lg font-semibold text-black/90">
            7. Disclaimers
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-black/70">
            The Service is provided “as is” without warranties of any kind. We
            do not guarantee uninterrupted availability, accuracy of
            translations, or fitness for a particular purpose.
          </p>

          <h2 className="mt-6 text-lg font-semibold text-black/90">
            8. Limitation of Liability
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-black/70">
            To the maximum extent permitted by law, Nuance Translate and its
            operators will not be liable for any indirect, incidental, special,
            consequential, or punitive damages, or any loss of data or profits,
            arising from your use of the Service.
          </p>

          <h2 className="mt-6 text-lg font-semibold text-black/90">
            9. Termination
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-black/70">
            We may suspend or terminate access to the Service at any time if we
            reasonably believe you have violated these Terms or if needed to
            protect the Service.
          </p>

          <h2 className="mt-6 text-lg font-semibold text-black/90">
            10. Changes
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-black/70">
            We may update these Terms from time to time. Continued use after an
            update means you accept the updated Terms.
          </p>

          <h2 className="mt-6 text-lg font-semibold text-black/90">
            11. Contact
          </h2>
          <p className="mt-2 text-sm leading-relaxed text-black/70">
            For questions about these Terms, contact the site owner.
          </p>
        </div>
      </section>
    </main>
  );
}